import React, { useState } from 'react';
import Gallery from '../components/Gallery';
import VideoCompare from '../components/VideoCompare';
const Home: React.FC = () => {
  const resultItems = [
    {
      src: '/assets/metrics/met3r.png',
      thumbnail: '/assets/metrics/met3r.png'
    },
    {
      src: '/assets/metrics/tsed.png',
      thumbnail: '/assets/metrics/tsed.png'
    },
    {
      src: '/assets/metrics/fvd.png',
      thumbnail: '/assets/metrics/fvd.png'
    }
  ];
  const videoItems = [
    {
      thumbnail: '/videos/sample_video.mp4',
      src: '/videos/sample_video.mp4',
      video: true,
      videoSrc: '/videos/sample_video.mp4'
    }
  ];
  const videoPairs = [
    {
      otherSrc: '/videos/french_manor_WJ.mp4',
      oursSrc: '/videos/output_french_manor_2.mp4',
      otherLabel: 'WonderJourney',
      oursLabel: 'Ours',  
    },
    {
      otherSrc: '/videos/output_cyberpunk_2_WJ.mp4',
      oursSrc: '/videos/output_cyberpunk_2.mp4',
      otherLabel: 'WonderJourney',
      oursLabel: 'Ours',
    }
  ];

  const [current, setCurrent] = useState(0);
  const pairCount = videoPairs.length;

  const handlePrev = () => {
    setCurrent((current + pairCount - 1) % pairCount);
  };

  const handleNext = () => {
    setCurrent((current + 1) % pairCount);
  };

  return (
    <>
      <section style={{ textAlign: 'center', padding: '4rem 0' }}>
        <h1>Title ASAGOHAN</h1>
        <p>
          Y. Katayama,&nbsp;R. Togo,&nbsp;K. Maeda,&nbsp;T. Ogawa,&nbsp;M. Haseyama
        </p>
        <div>
          <a className="btn" href="#paper">Paper</a>
          <a className="btn" href="#arXiv">arXiv</a>
          <a className="btn" href="#code">Code </a>
          {/* <a className="btn" href="#codelvdm">Code (MV-LDM)</a> */}
        </div>
      </section>

      <section id="abstract">
        <h2>Abstract</h2>
        <p>
        Recent advances in scene generation have enabled the automatic synthesis of continuous 3D environments from a single image and accompanying text, presenting new possibilities for virtual space construction. However, text-driven scene generation that produces sequential views from a single image often struggles to maintain global spatial coherence. In this paper, we propose a method that enhances spatial consistency by (i) leveraging multiple intermediate images generated by a Native Multimodal Model (NMM) and (ii) incorporating interpolation that explicitly accounts for camera rotation. Assuming a fixed camera position rotating 360 degrees, our method generates seamless panoramic scenes with improved spatial integrity and visual consistency. Experimental results validate the effectiveness of our approach in producing coherent and visually consistent 3D scene sequences.
        </p>
      </section>

      <section id="method">
        <h2>Method</h2>
        <img
          src="/images/overview.png"
          alt="Method overview"
          style={{ width: '100%', margin: '1rem 0' }}
        />
        <p>
        </p>
      </section>

      <section id="results">
        <h2>Results on RealEstate10K</h2>
        <Gallery items={resultItems} />
      </section>

      <section id="comparison">
        <h2>Comparison with WonderJourney</h2>

        <button 
          onClick={handlePrev} 
          style={{
            position: 'absolute',
            left: '1rem',
            top: '50%',
            transform: 'translateY(-50%)'
          }}
          aria-label="Previous Example"
        >◀</button>
          {/* <VideoCompare
              oursSrc="/videos/output_french_manor_2.mp4"
              otherSrc="/videos/french_manor_WJ.mp4"
              // デフォルトラベルを使うなら以下は省略可
              // oursLabel="Ours"
              // otherLabel="WonderJourney"
          /> */}
        <VideoCompare
          otherSrc={videoPairs[current].otherSrc}
          oursSrc={videoPairs[current].oursSrc}
          otherLabel={videoPairs[current].otherLabel}
          oursLabel={videoPairs[current].oursLabel}
        />
        <button 
          onClick={handleNext} 
          style={{
            position: 'absolute',
            right: '1rem',
            top: '50%',
            transform: 'translateY(-50%)'
          }}
          aria-label="Next Example"
        >▶</button>


        </section>

      <section id="more_examples">
        <h2>More Examples</h2>
        <Gallery items={videoItems} />
      </section>
{/* 
      <section id="mapviz">
        <h2>MEt3R Map Visualizations</h2>
        <Gallery items={mapVizItems} />
      </section>

      <section id="ack">
        <h2>Acknowledgements</h2>
        <p>
          This project was partially funded by the Saarland/…
        </p>
      </section> */}

      <section id="bibtex">
        <h2>BibTeX</h2>
        <pre>
{`@misc{asim2024metr3r,
  title={MEt3R: Measuring Multi-View Consistency in Generated Images},
  author={Asim, Mohammad and Wewer, Christopher and Wimmer, Thomas and Schiele, Bernt and Lenssen, Jan Eric},
  year={2024},
  howpublished={\\url{https://geometric-rl.mpi-inf.mpg.de/met3r/}}
}`}
        </pre>
      </section>
    </>
  );
};

export default Home;
